services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5437:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./app:/app
    working_dir: /app
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000" ]
    depends_on:
      - db
    environment:
      DB_USER: postgres
      DB_PASSWORD: 12345
      DB_ENDPOINT: localhost
      DB_NAME: postgres
      DB_PORT: 5437

volumes:
  postgres_data:
